apiVersion: apps/v1
kind: Deployment
metadata:
  name: monosi-controller-manager
  namespace: monosi-system
  labels:
    control-plane: controller-manager
    app.kubernetes.io/name: monosi
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: controller-manager
      app.kubernetes.io/name: monosi
  template:
    metadata:
      labels:
        control-plane: controller-manager
        app.kubernetes.io/name: monosi
    spec:
      serviceAccountName: monosi-controller-manager
      terminationGracePeriodSeconds: 10
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: manager
          image: ghcr.io/sodiqscript111/monosi:latest
          imagePullPolicy: IfNotPresent
          command:
            - /manager
          args:
            - --health-probe-bind-address=:8081
            - --metrics-bind-address=:8080
            - --leader-elect
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            limits:
              cpu: 200m
              memory: 128Mi
            requests:
              cpu: 10m
              memory: 32Mi
